/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  safelist: [
    'flex-col',
    'flex-wrap',
    'gap-1',
    'gap-2',
    'gap-4',
    'gap-6',
    'gap-8',
    'gap-10',
    'justify-center',
    'justify-start',
    'justify-end',
    'justify-between',
    'justify-around',
    'items-center',
    'items-start',
    'items-end',
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'sm:grid-cols-4',
    'sm:grid-cols-5',
    'sm:grid-cols-6',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'md:grid-cols-5',
    'md:grid-cols-6',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'lg:grid-cols-5',
    'lg:grid-cols-6',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#4E9F3D',
        'secondary': '#1E5128',
        'dark': '#191A19',
        'light': '#D8E9A8',
        'info': '#87ceeb'
      },
      container: {
        padding: {
          DEFAULT: '1rem',
          sm: '2rem',
          lg: '4rem',
          xl: '2rem',
          '2xl': '2rem',
        },
        center: true,
      },
    },
  },
  plugins: [],
}
